[package]
name = "rust-emscripten-bug"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rust-emscripten-bug"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
